[package]
name = "aoc-2025"
version = "0.1.0"
authors = ["Julian Andrews <jandrews271@gmail.com>"]
edition = "2021"

[dependencies]
anyhow = "1.0.93"
rustc-hash = "2.1.1"
thiserror = "2.0.18"
# itertools = "0.13.0"
# num_enum = "0.7.3"
# rustc-hash = "2.1.0"

[features]
verbose = []
